# Mehmet Arif Biyik
## Week 10
### Python Numpy into


In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [3]:
arr = np.array([1,2 , 3,4, 5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr2 = np.array(50)

In [8]:
arr2

array(50)

In [9]:
print(arr2)

50


In [10]:
arr3 = np.array([1,2 ,3,4,5,6])

In [12]:
print(arr3)

[1 2 3 4 5 6]


In [21]:
arr4 = np.array([[1,2,3,4,5,6], [[11,22,33,44,55,66]]])
print(arr4)

[list([1, 2, 3, 4, 5, 6]) list([[11, 22, 33, 44, 55, 66]])]


/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [20]:
arr5 = np.array([ [[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]]])

In [22]:
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [23]:
print(arr2.ndim)

0


In [24]:
print(arr4.ndim)

1


In [25]:
print(arr5.ndim)

3


In [26]:
print(arr3)

[1 2 3 4 5 6]


In [27]:
print(arr3[-1])

6


In [30]:
print(arr5[0,1,1])

5


In [34]:
marr = np.array([1,2,3,4,5])

In [36]:
print(arr5[0, -1])

[4 5 6]


In [38]:
print(arr3)

[1 2 3 4 5 6]


In [39]:
print(arr3[:3])

[1 2 3]


In [40]:
print(arr3[-3:-1])

[4 5]


In [41]:
print(arr3[1:5:2])

[2 4]
